version: "3"
services:
  socketio:
    image: node:9-alpine
    volumes:
      - .:/code
    working_dir: /code
    user: node
    ports:
      - 8080:3000
    environment:
      REDIS_HOST: "redis"
      APPLICATIONS: "ae0dc034-21cf-447f-88da-cc0643369525:PHDw6kvgOKbvdby0Z7NLgSO9wcXGIBYW"
      AUTHENTIFICATION_URL: "http://docker.for.mac.host.internal:3000/api/v2/ping"
      AUTHORIZATION_URL: "http://docker.for.mac.host.internal:3000/websocket/authorize"
    command: "bin/dev"
  redis:
    image: redis:3-alpine
    ports:
      - 6379
